spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:banking}
    username: ${DB_USER:banking_user}
    password: ${DB_PASSWORD:banking_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:20}
      minimum-idle: ${DB_MIN_IDLE:10}
      idle-timeout: 300000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false

  cache:
    type: caffeine

logging:
  level:
    root: INFO
    com.guilherme.desafiointer: INFO

management:
  endpoint:
    health:
      show-details: never