spring:
  application:
    name: desafio-inter
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
    open-in-view: false

# Configurações de Cache (comum a todos os ambientes)
cache:
  config:
    names:
      - cotacoes
      - historicoTransacoes
      - totaisTransacoes
    default:
      expire-after-write: PT24H
      initial-capacity: 100
      maximum-size: 500
    cotacoes:
      expire-after-write: PT1H
      initial-capacity: 50
      maximum-size: 200
    historicoTransacoes:
      expire-after-write: PT24H
      initial-capacity: 100
      maximum-size: 500
    totaisTransacoes:
      expire-after-write: PT12H
      initial-capacity: 100
      maximum-size: 300

# Configurações de API e resiliência (comum)
api:
  cotacao:
    url: ${API_COTACAO_URL:https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata/CotacaoDolarDia(dataCotacao=@dataCotacao)}
    format: json
    timeout: ${API_TIMEOUT:5000}

resilience4j:
  retry:
    instances:
      cotacaoRetry:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  circuitbreaker:
    instances:
      cotacaoCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

# Configurações de monitoramento (comum)
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,caches,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
    metrics:
      enabled: true
    prometheus:
      enabled: true