apiVersion: v1
kind: Service
metadata:
  name: remessa-api-service
  labels:
    app: remessa-api
    tier: backend
spec:
  selector:
    app: remessa-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer