services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: desafio-inter-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
